DROP TABLE IF EXISTS EVALUATION;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS PROPOSITION;
DROP TABLE IF EXISTS ESCALE;
DROP TABLE IF EXISTS TRAJET;
DROP TABLE IF EXISTS VOITURE;
DROP TABLE IF EXISTS PASSAGER;
DROP TABLE IF EXISTS CONDUCTEUR;
DROP TABLE IF EXISTS ETUDIANT;

-- Drop database
DROP DATABASE IF EXISTS covoiturage_db;


-- Drop triggers
DROP TRIGGER IF EXISTS ajout_voiture;
DROP TRIGGER IF EXISTS ajout_trajet_matricule;
DROP TRIGGER IF EXISTS ajout_trajet_dates;
DROP TRIGGER IF EXISTS ajout_passager_reservation;
DROP TRIGGER IF EXISTS ajout_passager_proposition;
DROP TRIGGER IF EXISTS delete_car;
DROP TRIGGER IF EXISTS delete_car_warning;
DROP TRIGGER IF EXISTS update_nbr_escale;
DROP TRIGGER IF EXISTS valid_escale_resa;
DROP TRIGGER IF EXISTS limit_booking_update;
DROP TRIGGER IF EXISTS limit_booking_insert;
DROP TRIGGER IF EXISTS modify_reservation_compl;
DROP TRIGGER IF EXISTS modify_escale_compl;
DROP TRIGGER IF EXISTS modify_trajet_compl;


