-- Update reservation 
UPDATE RESERVATION SET VALIDATION_RESERVATION = ? WHERE NUM_PASSAGER = ? AND NUM_TRAJET = ?;

-- Update voiture //$columnName représente l'attribut à mettre à jour
UPDATE VOITURE SET $columnName = ? WHERE NUM_IMMATRICULE = ?;

-- Update escale
UPDATE ESCALE SET VALIDATION_ESCALE = ? WHERE NUM_ESCALE = ?;

-- Update evaluation
UPDATE EVALUATION SET NOTE = ? WHERE NUM_ETUDIANT_EVALUE = ? AND NUM_TRAJET = ? AND NUM_ETUDIANT_EVALUATEUR = ?;

-- Update evaluation if it exists
INSERT INTO EVALUATION (NUM_ETUDIANT_EVALUE, NUM_TRAJET, NUM_ETUDIANT_EVALUATEUR, NOTE) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE NOTE = ?;